### ISSUE TITLE
conflict when using module with latest pe

### ISSUE THREAD

**Issue by micah-uber** [nanliu/puppet-staging#56]
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: File[/opt/staging] is already declared in file /etc/puppetlabs/puppet/environments/production/modules/staging/manifests/init.pp:28; cannot redeclare at /opt/puppet/share/puppet/modules/pe_staging/manifests/init.pp:25 on node hostname.internal
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by nanliu** [comment]
See notes in #38
